version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 183461
      MYSQL_DATABASE: itemsDB
      MYSQL_USER: syydmr
      MYSQL_PASSWORD: 183461
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local


